# Generated by Django 3.0.8 on 2020-07-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='titulo',
            new_name='title',
        ),
    ]
